version: "3"
services:
  reverseproxy:
      image: dejavxtrem/reverseproxy
      ports:
          - 8080:8080
      restart: always
      depends_on:
        - backend-user
        - backend-feed     
  backend-user:
    image: dejavxtrem/udagram-microservice-user
    environment:
      POSTGRES_USERNAME: $POSTGRES_USERNAME
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD 
      POSTGRES_DATABASE: $POSTGRES_DATABASE
      POSTGRES_DATABASE_HOST: $POSTGRES_DATABASE_HOST
      AWS_REGION: $AWS_REGION 
      AWS_PROFILE: $AWS_PROFILE 
      AWS_MEDIA_BUCKET: $AWS_MEDIA_BUCKET
      SECRET : $SECRET 
      URL: "http://localhost:8100"
  backend-feed:
    image: dejavxtrem/udagram-microservice-feed
    volumes:
      - $HOME/.aws:/root/.aws
    environment:
      POSTGRES_USERNAME: $POSTGRES_USERNAME
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD 
      POSTGRES_DATABASE: $POSTGRES_DATABASE 
      POSTGRES_DATABASE_HOST: $POSTGRES_DATABASE_HOST
      AWS_REGION: $AWS_REGION 
      AWS_PROFILE: $AWS_PROFILE 
      AWS_MEDIA_BUCKET: $AWS_MEDIA_BUCKET
      SECRET : $SECRET 
      URL: "http://localhost:8100"
  frontend:
    image: dejavxtrem/udagramfrontend
    ports:
      - "8100:80"