version: "3"
services:
  reverseproxy:
    build:
      context: .
    image: dejavxtrem/reverseproxy 
  backend_user:
    build:
      context: ../../udacity-c3-restapi-user
    image: dejavxtrem/udagram-microservice-user
  backend_feed:
    build:
      context: ../../udacity-c3-restapi-feed  
    image: dejavxtrem/udagram-microservice-feed
  frontend:
    build:
      context: ../../udagram-frontend 
    image: dejavxtrem/udagramfrontend